---
driver:
  name: podman

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: /usr/sbin/init
    privileged: true
    user: root
    pre_build_image: true
    tty: true
    tmpfs:
      - /tmp:rw,mode=1777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
  config_options:
    defaults:
      remote_tmp: /tmp

verifier:
  name: ansible

scenario:
  name: podman
  test_sequence:
    - syntax
    - create
    - converge
    - verify
    - destroy
